---
# This playbook configures a server with
#  - nfs-service

# The flow of this playbook
#
# register to RHN (tag: rhn_reg)
# additional Storage Config (tag: storage_setup)
# NFS config (tag: nfs_setup)
#
# Use skip tags if you want skip one of the above steps

- name: Install nfs Server
  hosts: fileserver
  become: true

  vars:
    # subscription mgmgt
    #
    reg_activation_key: "{{ sap_rhsm_activationkey }}"
    reg_organization_id: "{{ sap_rhsm_org_id }}"
    repositories:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms

    # RHN Server
    exportdirs:
      - /export/sap-software: '*(ro)'
      - /export/hana/shared: '*(rw)'

  tasks:
    - name: Ensure Correct subscription and repositories
      include_role:
        name: mk-ansible-roles.subscribe_rhn
      tags:
        - rhn_reg

    - name: get storage pool setup from server definition
      set_fact:
         storage_pools: "{{ server_def | selectattr('name', 'equalto', inventory_hostname) | sum(attribute='storage_pools', start=[]) }}"
      tags:
        - storage_setup

    - name: Ensure storage is configured correctly
      include_role:
        name: redhat.rhel_system_roles.storage
      tags:
        - storage_setup

    - name: Ensure nfs-server is configured correctly
      include_role:
         name: mk-ansible-roles.setup_nfs_server
      tags:
        - nfs_setup
