---
# This playbook configures a server with
#  - nfs-service

- name: Install nfs Server
  hosts: fileserver
  become: true

  vars:
    # subscription mgmgt
    #
    reg_activation_key: "{{ sap_rhsm_activationkey }}"
    reg_organization_id: "{{ sap_rhsm_org_id }}"
    repositories:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms

    # RHN Server
    exportdirs:
      - /export/sap-software: '*(ro)'
      - /export/hana/shared: '*(rw)'

  tasks:
    # TODO:
    # Check proper hostname and /etc/host setting

    - name: Ensure Correct subscription and repositories
      include_role:
        name: mk-ansible-roles.subscribe_rhn

    - name: get storage pool setup from server definition
      set_fact:
         storage_pools: "{{ vmware_machines | selectattr('name', 'equalto', inventory_hostname) | sum(attribute='storage_pools', start=[]) }}"

    - name: Ensure storage is configured correctly
      include_role:
        name: redhat.rhel_system_roles.storage

    - name: Ensure nfs-server is configured correctly
      include_role:
         name: mk-ansible-roles.setup_nfs_server
