---
####################################################
#
# Phase 2: Basic OS Setup
#
# This playbook covers the following configuration steps
#  - subscription and repositories
#  - network setup
#  - storage customization

# For our demo, we do not need to install additional packages,
# configure special services, monitoring and backup etc.
# we are good with what the standard image provides

# We need to provide this script the storage configuration
# for each machine. Hence we need to extend the dictionary "gcp_machines"
# with its individual storage configuration for the second disk, e.g.:

#   gcp_machines:
#           - name: server-name
#             [...]
#             storage_pools:
#               - name: volume_name
#                 disks:
#                  - sdb
#                 volumes:
#                   - name: data
#                     size: "128 GiB"
#                     mount_point: "/hana/data"
#                     fs_type: xfs
#                     state: present
#                   - name: log
#                     size: "64 GiB"
#                     mount_point: "/hana/log"
#                     fs_type: xfs
#                     state: present

# Have a look at the documention of the storage role for more configuration options

- name: Ensure Servers are booted and reachable
  hosts: all
  gather_facts: false
  become: false
  tasks:
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ ansible_host }}"
      port: 22
      delay: 30
      state: started
      timeout: 480
    delegate_to: localhost

- name: Phase 2 - basic OS Setup
  hosts: hanas,s4hanas
  become: true

  # Default variables for the playbooks can be set here
  # and can be overwritten in the template file
  vars:
    reg_osrelease: 8.6
    repositories:
      - rhel-8-for-ppc64le-baseos-e4s-rpms
      - rhel-8-for-ppc64le-appstream-e4s-rpms
      - rhel-8-for-ppc64le-sap-solutions-e4s-rpms
      - rhel-8-for-ppc64le-sap-netweaver-e4s-rpms
      - rhel-8-for-ppc64le-highavailability-e4s-rpms

  tasks:
    - name: Ensure Correct subscription and repositories
      include_role:
        name: mk-ansible-roles.subscribe_rhn

    - name: Ensure timeserver is configured
      include_role:
        name: redhat.redhat_system_roles.timesync
      when:
        - timesync_ntp_servers is defined
