---
####################################################
#
# Phase 2: Basic OS Setup
#
# This playbook covers the following configuration steps
#  - subscription and repositories
#  - network setup

# Have a look at the documention of the storage role for more configuration options

- name: Ensure Servers are booted and reachable
  hosts: all
  gather_facts: false
  become: false
  tasks:
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ ansible_host }}"
      port: 22
      delay: 30
      state: started
      timeout: 480
    delegate_to: localhost

- name: Phase 2 - basic OS Setup
  hosts: hanas,s4hanas
  become: true

  # Default variables for the playbooks can be set here
  # and can be overwritten in the template file
  vars:
    reg_osrelease: 8.6
    repositories:
      - rhel-8-for-ppc64le-baseos-e4s-rpms
      - rhel-8-for-ppc64le-appstream-e4s-rpms
      - rhel-8-for-ppc64le-sap-solutions-e4s-rpms
      - rhel-8-for-ppc64le-sap-netweaver-e4s-rpms
      - rhel-8-for-ppc64le-highavailability-e4s-rpms
    ibm_power_tools_url: https://public.dhe.ibm.com/software/server/POWER/Linux/yum/OSS/RHEL/8/ppc64le
    ibm_at_url: https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/redhat/RHEL8

  tasks:
    - name: Ensure Correct subscription and repositories
      include_role:
        name: mk-ansible-roles.subscribe_rhn

    - name: Ensure EPEL is disabled because it conflicts with minor release pinning
      ansible.builtin.yum_repository:
        name: 'epel'
        state: absent
      notify: Yum-clean-metadata

    - name: Ensure correct IBM Powertools repository is configured
      ansible.builtin.yum_repository:
        name: IBM_Power_Tools
        description: "IBM_Power_Tools for RHEL 8"
        baseurl: "{{ ibm_power_tools_url }}"
        gpgcheck: false
        enabled: true
        file: ibm-power
      notify: Yum-clean-metadata

    # - name: Update System to the required RHEL release
    #  dnf:
    #    name: '*'
    #    state: latest

    - name: Ensure timeserver is configured
      include_role:
        name: redhat.redhat_system_roles.timesync
      when:
        - timesync_ntp_servers is defined

  handlers:
    - name: Yum-clean-metadata
      ansible.builtin.command: yum clean metadata
      args:
        warn: false
