---
- name: "Phase 03-C and 03-D -Setup HANA System Replication"
  hosts: hanas
  become: true

#  vars:
#    sap_domain: example.com
#
#    sap_hana_sid: 'DB1'
#    sap_hana_instance_number: '00'
#    sap_hana_install_master_password: 'my_hana_password'
#    # It is recommended to use vault instead of plain text passwords. Example please check README
#
#    ### Cluster Definition
#    ha_cluster_cluster_name: cluster1
#    ha_cluster_hacluster_password: 'my_hacluster'
#    
#    sap_hana_cluster_nodes:
#      - node_name: hana1
#        node_ip: "{{ hostvars['hana1'].ansible_host }}"
#        node_role: primary
#        hana_site: DC01
#
#      - node_name: hana2
#        node_ip: "{{ hostvars['hana2'].ansible_host }}"
#        node_role: secondary
#        hana_site: DC02
#
#    sap_hana_vip: 
#        primary: 10.14.11.5 ## Change to Virtual IP of cluster (needs to be in hosts or DNS)
#
#    sap_ha_pacemaker_cluster_stonith_custom:
#      - name: "fence_for_vmware"
#        agent: "stonith:fence_vmware_rest"
#        options:
#          pcmk_host_list: 'hana1,hana2' 
#          ssl_insecure: 1 
#          ssl: 1
#          ipaddr: "{{ lookup('env', 'VMWARE_HOST')}}"
#          login: "{{lookup('env','VMWARE_USER')}}"
#          passwd: "{{lookup('env','VMWARE_PASSWORD')}}"
#
# Access the IP Address of a particular hostname:
# hostvars[inventory_hostname].ansible_host
#
  pre_tasks:
    - name: Copy pre-release fence_openstack
      copy:
        src: usr/sbin/fence_openstack
        dest: /usr/sbin/fence_openstack
        owner: root
        group: root
        mode: 0755


  roles:
    - community.sap_install.sap_ha_install_hana_hsr
    - community.sap_install.sap_ha_pacemaker_cluster
