---
########################################################
# Delete created LPARS
#
# After running this playbook you will have
# all LPARS deleted that are defined in:
#   server_def:
#           - name: server-name

- name: 99 - Delete all hosts from server_def dict
  hosts: localhost
  gather_facts: false

  tasks:
  - name: delete LPARs
    include_role:
      name: powervc_vm_delete
    vars:
      vm_delete_name: "{{ item.name }}"
    loop: "{{ server_def }}"
