---
# Phase 3 - step B
#
# This playbook downloads the hana software defined
# in the list {{ sap_hana_software }} to {{ sap_hana_install_software_directory }}
#
# The role sap_hana_install unpacks the software in {{ sap_hana_install_software_directory }}
# Then it calls the installation of SAP HANA with the configured paramters

- name: Phase 3-B - Install Hana
  hosts: rha-nfs-server
  become: true

  tasks:

          # - name: include GCSFUSE
          # include_role:
          # name: google.cloud.gcsfuse

   - name: debug
     ansible.builtin.debug:
     msg: |
         the value of foo.txt is {{ lookup('community.google.gcp_storage_file',
         bucket='rh-ava-packages', src='sap/SAPCAR_1115-70006178.EXE',
         auth_kind='serviceaccount') }}


   - name: copy HANA images from bucket locally
     include_role:
       name: gcp_copy_file_from_bucket
     vars:
       gcp_copy_file_from_bucket_bucketname: "rh-ava-packages"
       gcp_copy_file_from_bucket_filename: "sap/{{ item }}"
       gcp_copy_file_from_bucket_dest: "{{ sap_hana_install_software_directory }}"
     loop: "{{ sap_hana_install_sarfiles }}"

    # name: execute the SAP Hana Installation
    # include_role:
    #   name: community.sap_install.sap_hana_install
