---
# Phase 3 - step B
#
# This playbook downloads the hana software defined
# in the list {{ sap_hana_software }} to {{ sap_hana_install_software_directory }}
#
# The role sap_hana_install unpacks the software in {{ sap_hana_install_software_directory }}
# Then it calls the installation of SAP HANA with the configured paramters

- name: Phase 3-B - Install Hana
  hosts: rha-hana
  become: true

  tasks:

    - name: Print Owner
      debug:
              msg: "GCP Service EMAIL {{ lookup('env','GCE_EMAIL') }}"

    - name: prerequisites
      pip:
        name: google-cloud-storage
        state: present
