---
- name: Stop a single Google VM by name
  hosts: localhost
  gather_facts: false

  vars:
    - gcp_vm_name: rha-hana

  tasks:
    - name: Power off a GCP VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ gcp_vm_name }}"
        zone: "{{ gcp_vm_zone }}"
        auth_kind: serviceaccount
        state: stopped
