---
- name: Start Google VM
  hosts: all
  gather_facts: false

  tasks:
    - name: Get vm informamtion
      google.cloud.gcp_compute_instance_info:
        zone: "{{ gcp_vm_zone }}"
        filters:
          - name = "{{ inventory_hostname }}"
        auth_kind: serviceaccount
      register: gcp_vm_info
      delegate_to: localhost

    - name: Debug labels
      ansible.builtin.debug:
        var: gcp_vm_info.resources[0].labels

    - name: Start a GCP VM instance which is currently stopped
      when: gcp_vm_info.resources[0].status == "TERMINATED"
      google.cloud.gcp_compute_instance:
        name: "{{ inventory_hostname }}"
        zone: "{{ gcp_vm_zone }}"
        auth_kind: serviceaccount
        status: running
        labels: "{{ gcp_vm_info.resources[0].labels }}" # Workaround to keep the labels
      delegate_to: localhost
