---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Build a list of all the folders with the type VIRTUAL_MACHINE and called vm
    vmware.vmware_rest.vcenter_folder_info:
    filter_type: VIRTUAL_MACHINE
    filter_names:
      - vm
    register: my_folders

  - debug:
         var: my_folders
