---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Retrieve a list of all the datastores
    vmware.vmware_rest.vcenter_datastore_info:
    register: my_datastores

  - debug:
         var: my_datastores
