---
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Collect the list of the datacenters
    community.vmware.vmware_datacenter_info:
      validate_certs: false
    register: my_datacenters

  - debug:
         var: my_datacenters
