---
- name: Unregister system from RHN
  ansible.builtin.command: /usr/bin/subscription-manager unregister
  delegate_to: "{{ vm_ip }}"
  failed_when: false
  changed_when: true
  ignore_unreachable: true

- name: "Ensure {{ vm_name }} is removed"
  openstack.cloud.server:
    auth: "{{ os_add_auth | default(omit) }}"
    validate_certs: false
    state: absent
    name: "{{ vm_name }}"
    timeout: 600

- name: Ensure network port is removed
  openstack.cloud.port:
    auth: "{{ os_add_auth | default(omit) }}"
    validate_certs: false
    state: absent
    name: "{{ vm_name }}-port1"