---
# find out the cluster_id for the clusters
- hosts: localhost
  gather_facts: false

  tasks:
  - name: Build a list of all the clusters
    vmware.vmware_rest.vcenter_cluster_info:
    register: all_the_clusters

  - debug:
         var: all_the_clusters

  - name: retrieve detailed info about all clusters
    vmware.vmware_rest.vcenter_cluster_info:
      cluster: "{{ item.cluster }}"
    loop: "{{ all_the_clusters.value }}"
    register: my_cluster_info

  - debug:
         var: my_cluster_info
